package com.arvs.testing.audio

import kotlin.math.PI
import kotlin.math.exp
import kotlin.math.sin

/**
 * The §119 audio test fixtures, synthesised.
 *
 * §119 names nine: silence, sine, bass sweep, white noise, impulse, drums, stereo, clipping,
 * very quiet signal. §115 (license safety) is why they are *generated* rather than committed:
 * no third-party audio enters the repository, and the plan's test strategy states the same
 * requirement — "generated by a checked-in generator with fixed parameters".
 *
 * **Every generator here is deterministic.** That is not a nicety; it is what makes §9.1's
 * determinism suite and the golden analysis vectors possible at all. In particular the noise
 * generator uses its own seeded PRNG rather than `kotlin.random.Random`, whose algorithm is
 * not contractually fixed across Kotlin versions — a golden vector cut against it could break
 * on a toolchain upgrade with no code change, which is exactly the permanently-flaky suite
 * §123 warns about.
 *
 * Amplitudes are normalised floats in `[-1, 1]`, matching
 * [com.arvs.core.model.PcmBuffer].
 */
public object SignalGenerators {

    /** §119 "silence" — all zeros. Must produce zeroed features with no NaN or Inf. */
    public fun silence(frameCount: Int): FloatArray = FloatArray(frameCount)

    /**
     * §119 "sine" — a pure tone.
     *
     * The analytic reference for several suites: RMS is exactly `amplitude / √2`, peak is
     * `amplitude`, and the magnitude spectrum has a single non-zero bin at [frequencyHz].
     */
    public fun sine(
        frameCount: Int,
        frequencyHz: Double,
        sampleRateHz: Int,
        amplitude: Float = 0.5f,
        phaseRadians: Double = 0.0,
    ): FloatArray {
        require(frequencyHz > 0) { "frequencyHz must be positive: $frequencyHz" }
        val step = 2.0 * PI * frequencyHz / sampleRateHz
        return FloatArray(frameCount) { n -> (amplitude * sin(n * step + phaseRadians)).toFloat() }
    }

    /**
     * §119 "bass sweep" — a linear-frequency chirp through the low end.
     *
     * Phase is accumulated rather than computed as `sin(2π·f(t)·t)`. The closed form is the
     * classic chirp mistake: it produces an instantaneous frequency of `2·f(t)`, so a sweep
     * intended to end at 200 Hz actually ends at 400 Hz and every band-energy expectation
     * derived from it is quietly wrong.
     */
    public fun bassSweep(
        frameCount: Int,
        startHz: Double,
        endHz: Double,
        sampleRateHz: Int,
        amplitude: Float = 0.5f,
    ): FloatArray {
        require(startHz > 0 && endHz > 0) { "sweep endpoints must be positive" }
        val out = FloatArray(frameCount)
        var phase = 0.0
        for (n in 0 until frameCount) {
            val t = if (frameCount <= 1) 0.0 else n.toDouble() / (frameCount - 1)
            val instantaneousHz = startHz + (endHz - startHz) * t
            out[n] = (amplitude * sin(phase)).toFloat()
            phase += 2.0 * PI * instantaneousHz / sampleRateHz
        }
        return out
    }

    /**
     * §119 "white noise" — uniform in `[-amplitude, amplitude]`, from a fixed seed.
     *
     * Uses [DeterministicNoise], not the platform PRNG, so the same seed yields the same
     * samples on every Kotlin version and every device.
     */
    public fun whiteNoise(frameCount: Int, seed: Long = DEFAULT_NOISE_SEED, amplitude: Float = 0.5f): FloatArray {
        val noise = DeterministicNoise(seed)
        return FloatArray(frameCount) { (noise.nextUnitBipolar() * amplitude).toFloat() }
    }

    /**
     * §119 "impulse" — a single full-scale sample, zeros elsewhere.
     *
     * The analytic reference for spectral flatness: a unit impulse has a perfectly flat
     * magnitude spectrum, so any deviation is the analyser's, not the signal's.
     */
    public fun impulse(frameCount: Int, position: Int = 0, amplitude: Float = 1.0f): FloatArray {
        require(position in 0 until frameCount) { "impulse position $position out of range" }
        return FloatArray(frameCount).also { it[position] = amplitude }
    }

    /**
     * §119 "drums" — a synthetic percussive pattern at a known tempo.
     *
     * Each hit is an exponentially decaying burst of noise plus a low sine body, which is
     * enough structure for onset detection and tempo estimation (§21) to have something real
     * to find. The tempo is exact by construction, so beat tests assert against a known
     * answer rather than against whatever the analyser reported first.
     */
    public fun drumPattern(
        frameCount: Int,
        sampleRateHz: Int,
        tempoBpm: Double = 120.0,
        seed: Long = DEFAULT_NOISE_SEED,
    ): FloatArray {
        require(tempoBpm > 0) { "tempoBpm must be positive: $tempoBpm" }
        val out = FloatArray(frameCount)
        val framesPerBeat = (60.0 / tempoBpm * sampleRateHz).toInt()
        if (framesPerBeat <= 0) return out

        val noise = DeterministicNoise(seed)
        val decayPerFrame = 30.0 / sampleRateHz
        var beatStart = 0
        while (beatStart < frameCount) {
            val hitLength = minOf(framesPerBeat, frameCount - beatStart)
            for (n in 0 until hitLength) {
                val envelope = exp(-n * decayPerFrame)
                if (envelope < 1e-4) break
                val body = sin(2.0 * PI * 80.0 * n / sampleRateHz)
                val transient = noise.nextUnitBipolar()
                out[beatStart + n] = (envelope * (0.7 * body + 0.3 * transient)).toFloat()
            }
            beatStart += framesPerBeat
        }
        return out
    }

    /**
     * §119 "clipping" — a signal driven past full scale and hard-limited.
     *
     * Peak must read exactly 1.0. The generator clamps rather than letting values exceed
     * `[-1, 1]`, because a "clipped" fixture that is actually out of range tests the
     * analyser's handling of invalid input, which is a different question.
     */
    public fun clipping(
        frameCount: Int,
        frequencyHz: Double,
        sampleRateHz: Int,
        driveGain: Float = 4.0f,
    ): FloatArray {
        val clean = sine(frameCount, frequencyHz, sampleRateHz, amplitude = 1.0f)
        return FloatArray(frameCount) { n -> (clean[n] * driveGain).coerceIn(-1.0f, 1.0f) }
    }

    /**
     * §119 "very quiet signal" — near the noise floor.
     *
     * Deliberately small enough to expose denormal collapse and any premature rounding to
     * zero, while staying representable in float without becoming subnormal itself.
     */
    public fun veryQuiet(
        frameCount: Int,
        frequencyHz: Double,
        sampleRateHz: Int,
        amplitude: Float = 1.0e-6f,
    ): FloatArray = sine(frameCount, frequencyHz, sampleRateHz, amplitude)

    /**
     * §119 "stereo" — interleaved, with **different** left and right content.
     *
     * §17.3 makes this fixture mandatory and states what it must prove: that L/R-differing
     * input produces exactly `0.5·L + 0.5·R`, repeatably. A stereo fixture whose channels are
     * identical cannot distinguish a correct downmix from one that simply drops a channel,
     * which is the whole reason §17.3 calls this out.
     */
    public fun interleaveStereo(left: FloatArray, right: FloatArray): FloatArray {
        require(left.size == right.size) {
            "stereo channels must be the same length: ${left.size} vs ${right.size}"
        }
        val out = FloatArray(left.size * 2)
        for (n in left.indices) {
            out[n * 2] = left[n]
            out[n * 2 + 1] = right[n]
        }
        return out
    }

    /** The seed every noise-based fixture defaults to, so fixtures are reproducible by name. */
    public const val DEFAULT_NOISE_SEED: Long = 0x5EED_A11D_10E5L
}

/**
 * A small, fixed PRNG — SplitMix64.
 *
 * Chosen over `kotlin.random.Random` because the platform PRNG's algorithm is not a
 * contractual guarantee across Kotlin versions, and a golden analysis vector cut against a
 * PRNG that changes is a test that fails on a toolchain bump with no code change. SplitMix64
 * is ten lines, has published constants, and will still produce these exact bytes in a decade.
 */
public class DeterministicNoise(seed: Long) {
    private var state: Long = seed

    public fun nextLong(): Long {
        state += -0x61c8864680b583ebL // 0x9E3779B97F4A7C15
        var z = state
        z = (z xor (z ushr 30)) * -0x40a7b892e31b1a47L // 0xBF58476D1CE4E5B9
        z = (z xor (z ushr 27)) * -0x6b2fb644ecceee15L // 0x94D049BB133111EB
        return z xor (z ushr 31)
    }

    /** Uniform in `[-1, 1)`. */
    public fun nextUnitBipolar(): Double = (nextLong() ushr 11) * (2.0 / (1L shl 53)) - 1.0
}
